name: "project-rockers"

services:
    server:
        image: ankit8424/rockers-django:1.0.0
        container_name: rockers-django
        volumes:
            - rockers-volume:/app
            - rockers-static:/app/volume
        ports:
            - 8000:8000
        env_file:
            - .env
        depends_on:
            database:
                condition: service_healthy
        networks:
            - rockers-network
        command: gunicorn core.wsgi:application --bind=0.0.0.0:8000

    database:
        image: mysql:9.0
        container_name: rockers-db
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}

        volumes:
            - sql-volume:/var/lib/mysql
        networks:
            - rockers-network
        ports:
            - 3306:3306
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 5

    proxy-server:
        build:
            context: .
            dockerfile_inline: |
                FROM nginx:1.27.2
                RUN rm /etc/nginx/conf.d/default.conf
                COPY nginx.conf /etc/nginx/conf.d

        image: proxy-server
        container_name: proxy-server
        ports:
            - 80:80
        depends_on:
            - server
        networks:
            - rockers-network
        volumes:
            - rockers-static:/app/volume

volumes:
    rockers-volume:
        name: "rockers-volume"
    rockers-static:
        name: "rockers-static-vol"
    sql-volume:
        name: "sql-volume"

networks:
    rockers-network:
        driver: bridge
