services:
    server:
        build:
            dockerfile: dockerfile
        container_name: rockers-django
        command: gunicorn core.wsgi:application --bind=0.0.0.0:8000
        volumes:
            - main_volume:/app/volume
        expose:
            - 8000
        env_file:
            - .env
        depends_on:
            - database

    database:
        image: mysql:9.0
        container_name: rockers-db

        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}

        expose:
            - 3306

    nginx:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - server
        volumes:
            - main_volume:/app/volume

volumes:
    main_volume:
